platform: linux

image_resource:
  type: docker-image
  source:
    repository: williamsjt/ephemerol
    tag: latest

inputs:
  - name: source-files

run:
  path: sh
  args:
  - -exc
  - |
    cd ./source-files
    scan_output=`python -m ephemerol $RULEBASE_PATH $SOURCE_ZIP_PATH`
    exit `echo "$MINIMUM_SCAN_INDEX>$cloud_readiness_index" | bc`